[package]
name = "binance-rs-async"
version = "1.0.0"
license = "MIT OR Apache-2.0"
authors = ["Guillaume Balaine igosuki.github@gmail.com"]
edition = "2018"

description = "Async Rust Library for the Binance API"
keywords = ["cryptocurrency", "trading", "binance"]
documentation = "https://docs.rs/crate/binance-rs-async/"
repository = "https://github.com/Igosuki/binance-rs-async"
readme = "README.md"

[lib]
name = "binance"
path = "src/lib.rs"

[dependencies]
chrono = "0.4"
futures = "0.3"
hex = "0.4"
reqwest = { version = "0.11", features = ["json"] }
ring = "0.16"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_qs = "0.8"
thiserror = "1.0"
tungstenite = "0.14"
url = "2.2"

[dev-dependencies]
csv = "1.1"
env_logger = "0.9"
log = "0.4"
tokio = { version = "1", features = ["full"] }
tokio-test = "0.4"
