[package]
name = "binance-rs-async"
version = "1.0.0-beta.2"
license = "MIT OR Apache-2.0"
authors = ["Guillaume Balaine igosuki.github@gmail.com"]
edition = "2018"

description = "Async Rust Library for the Binance API"
keywords = ["cryptocurrency", "trading", "binance"]
documentation = "https://docs.rs/crate/binance-rs-async/"
repository = "https://github.com/Igosuki/binance-rs-async"
readme = "README.md"

[lib]
name = "binance"
path = "src/lib.rs"

[dependencies]
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_qs = "0.8"
ring = "0.16"
reqwest = { version = "0.11", features = ["json"] }
tungstenite = "0.13"
url = "2.1"
futures = "0.3"
chrono = "0.4"
thiserror = "1.0"

[dev-dependencies]
csv = "1.0"
tokio = { version = "1", features = ["full"] }
log = "0.4"
env_logger = "0.8"
tokio-test = "0.4.2"
